kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-devicehive-hazelcast
spec:
  selector:
    app: {{ .Release.Name }}-devicehive-hazelcast
  ports:
    - protocol: TCP
      port: 5701
      targetPort: hazelcast
