---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-devicehive-proxy
spec:
  selector:
    app: {{ .Release.Name }}-devicehive-proxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
...
