{{- if eq .Values.javaServer.bus "wsproxy" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-devicehive-ws-proxy-internal
spec:
  selector:
    app: {{ .Release.Name }}-devicehive-ws-proxy-internal
  ports:
    - protocol: TCP
      port: 3000
      targetPort: ws-proxy
{{- end }}
