apiVersion: v1
kind: Secret
metadata:
  name: {{ template "devicehive-cassandra-plugin.fullname" . }}
  labels:
    app: {{ template "devicehive-cassandra-plugin.name" . }}
    chart: {{ template "devicehive-cassandra-plugin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  cassandraUsername: {{ .Values.connection.username | b64enc | quote }}
  cassandraPassword: {{ .Values.connection.password | b64enc | quote }}
  pluginLogin: {{ .Values.plugin.login | b64enc | quote }}
  pluginPassword: {{ .Values.plugin.password | b64enc | quote }}

