{{ if .Values.rbac.create }}
{{- $serviceName := include "devicehive.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}
  labels:
#    app: {{ $serviceName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ end }}
